### ISSUE TITLE
Feature request: Option to show placeholder when no filtered results are available

### ISSUE THREAD

**Issue by maarten00** [dverleg/vanillafilter#1]
It would be great if I could pass a parameter with a selector or a callback to show a placeholder when there are no results after filtering.  
The placeholder would be visible by default, the script should hide it and show it when there are no results.  Optionally a callback could also be useful, but a selector would be fine for now.

**Comment by dverleg** [comment]
Will implement this feature as soon as possible

**Comment by dverleg** [comment]
Added in 1.6.0
