### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mnengerman** [dverleg/vanillafilter#2]
Hi Dennis,

Would be awesome if any `<element>` could be a trigger to toggle any target `<element>`. I would use it on a FAQ page i'm currently working on. Here I would like the question to be a toggle for the answer.

Thanks in advance!

**Comment by dverleg** [comment]
On the to-do list to add a 'single' option to the settings, or something similar, so you can enable displaying just 1 active element, instead of multipel.

Cheers!
